import {
  Database,
  GitMerge,
  BarChart3,
  ArrowUpDown,
  Copy,
  MapPin,
  Filter,
  Calculator,
  Columns,
  Edit3,
  Hash,
  FunctionSquare,
  Layers,
  ListFilter,
  FileDown,
  Sparkles,
  Users,
  CircleDot,
  // New icons for merged blocks
  GitBranch,
  Code2,
  BookOpen,
  RefreshCw,
  Shield,
  Building2,
  // Advanced transform icons
  Trophy,
  ArrowLeftRight,
  TrendingUp,
  Percent,
  Braces,
  Search,
  Wrench,
  RotateCcw,
  Calendar,
  Timer,
  Eraser,
  SplitSquareVertical,
  GitCompare,
  // Source icons
  Cloud,
  ExternalLink,
  Share2,
  // Python data engineering icons
  Cog,
  Play,
  Zap,
  // Template icons
  Clock,
  // ML Training icons
  Brain,
  Crosshair,
  Activity,
  LineChart,
  FileSearch,
  // AI SQL function icons (Sparkles already imported above)
  MessageSquare,
  Languages,
  Tags,
  // New block icons
  BarChart,
  type LucideIcon,
} from 'lucide-react';
// Category type for palette grouping
export type ETLCategory = 'source' | 'transform' | 'transform_advanced' | 'destination' | 'python' | 'ml_training' | 'ai_functions' | 'templates';

// ETL Block definition
export interface ETLBlockDefinition {
  id: string;
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  category: ETLCategory;
  color: string;
  bgColor: string;
  borderColor: string;
  hasInput: boolean;
  hasOutput: boolean;
  minInputs: number;
  maxInputs: number;
  tooltip?: string;
}

// All ETL blocks aligned with new backend component templates
export const ETL_BLOCKS: ETLBlockDefinition[] = [
  // ============================================
  // SOURCE BLOCKS
  // ============================================
  {
    id: 'source',
    type: 'source',
    label: 'Source',
    description: 'Read data from Snowflake table',
    icon: Database,
    category: 'source',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    borderColor: 'border-green-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a Snowflake table',
  },

  // CDC Merge — consumes a Snowflake Stream and applies MERGE INTO target table
  {
    id: 'cdc_merge',
    type: 'cdc_merge',
    label: 'CDC Merge',
    description: 'Process Snowflake Stream with MERGE INTO pattern',
    icon: GitMerge,
    category: 'source',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/20',
    borderColor: 'border-emerald-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Consume a Snowflake Stream and apply MERGE INTO on the target table (CDC pattern)',
  },

  // ============================================
  // TRANSFORM BLOCKS
  // ============================================
  {
    id: 'join',
    type: 'join',
    label: 'Join',
    description: 'Join two data sources',
    icon: GitMerge,
    category: 'transform',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    borderColor: 'border-amber-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 2,
    maxInputs: 2,
    tooltip: 'Join two data sources on matching keys (INNER, LEFT, RIGHT, FULL, CROSS)',
  },
  {
    id: 'filter',
    type: 'filter',
    label: 'Filter',
    description: 'Filter rows by conditions',
    icon: Filter,
    category: 'transform',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Filter rows based on column conditions (WHERE clause)',
  },
  {
    id: 'aggregate',
    type: 'aggregate',
    label: 'Aggregate',
    description: 'GROUP BY + aggregations',
    icon: BarChart3,
    category: 'transform',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    borderColor: 'border-purple-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Group data and calculate aggregations (SUM, AVG, COUNT, MIN, MAX)',
  },
  {
    id: 'select',
    type: 'select',
    label: 'Select',
    description: 'Select specific columns',
    icon: Columns,
    category: 'transform',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Select specific columns to include in output',
  },
  {
    id: 'rename',
    type: 'rename',
    label: 'Rename',
    description: 'Rename columns',
    icon: Edit3,
    category: 'transform',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50 dark:bg-teal-900/20',
    borderColor: 'border-teal-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Rename one or more columns',
  },
  {
    id: 'cast',
    type: 'cast',
    label: 'Cast',
    description: 'Cast column types',
    icon: Hash,
    category: 'transform',
    color: 'text-rose-600',
    bgColor: 'bg-rose-50 dark:bg-rose-900/20',
    borderColor: 'border-rose-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Cast column data types (e.g., STRING to DATE)',
  },
  {
    id: 'formula',
    type: 'formula',
    label: 'Formula',
    description: 'Add calculated columns',
    icon: FunctionSquare,
    category: 'transform',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Add new columns with calculated expressions',
  },
  {
    id: 'sort',
    type: 'sort',
    label: 'Sort',
    description: 'Order by columns',
    icon: ArrowUpDown,
    category: 'transform',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    borderColor: 'border-indigo-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Sort data by one or more columns (ORDER BY)',
  },
  {
    id: 'union',
    type: 'union',
    label: 'Union',
    description: 'Combine multiple datasets',
    icon: Layers,
    category: 'transform',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/20',
    borderColor: 'border-cyan-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 2,
    maxInputs: 10, // Support multiple inputs
    tooltip: 'Combine multiple datasets vertically (UNION / UNION ALL)',
  },
  {
    id: 'distinct',
    type: 'distinct',
    label: 'Distinct',
    description: 'Remove duplicate rows',
    icon: Copy,
    category: 'transform',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50 dark:bg-pink-900/20',
    borderColor: 'border-pink-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Remove duplicate rows (SELECT DISTINCT)',
  },
  {
    id: 'limit',
    type: 'limit',
    label: 'Limit',
    description: 'Limit number of rows',
    icon: ListFilter,
    category: 'transform',
    color: 'text-slate-600',
    bgColor: 'bg-slate-50 dark:bg-slate-900/20',
    borderColor: 'border-slate-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Limit the number of output rows (LIMIT)',
  },

  // ============================================
  // ML / AI DEFAULT CAPABILITIES (Recommendation, Segmentation, Clustering)
  // ============================================
  {
    id: 'recommendation',
    type: 'recommendation',
    label: 'Recommendation',
    description: 'Score or rank items (Cortex LLM or custom model)',
    icon: Sparkles,
    category: 'transform',
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
    borderColor: 'border-fuchsia-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Add recommendation scores using Cortex or custom model; output scored/ranked data',
  },
  {
    id: 'segmentation',
    type: 'segmentation',
    label: 'Segmentation',
    description: 'Assign segments (RFM, rules, or model)',
    icon: Users,
    category: 'transform',
    color: 'text-lime-600',
    bgColor: 'bg-lime-50 dark:bg-lime-900/20',
    borderColor: 'border-lime-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Segment data by rules, RFM, or ML model; add segment column',
  },
  {
    id: 'clustering',
    type: 'clustering',
    label: 'Clustering',
    description: 'Assign clusters (Cortex ML or k-means)',
    icon: CircleDot,
    category: 'transform',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    borderColor: 'border-amber-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Cluster data using Cortex ML or SQL k-means; add cluster_id column',
  },

  // ============================================
  // DESTINATION BLOCKS
  // ============================================
  {
    id: 'destination',
    type: 'destination',
    label: 'Destination',
    description: 'Write to Snowflake table',
    icon: MapPin,
    category: 'destination',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/20',
    borderColor: 'border-emerald-400',
    hasInput: true,
    hasOutput: false,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Write data to a target Snowflake table (overwrite, append, or merge)',
  },
  {
    id: 'export_file',
    type: 'export_file',
    label: 'Export File',
    description: 'Export to file',
    icon: FileDown,
    category: 'destination',
    color: 'text-sky-600',
    bgColor: 'bg-sky-50 dark:bg-sky-900/20',
    borderColor: 'border-sky-400',
    hasInput: true,
    hasOutput: false,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Export data to CSV, Parquet, or JSON file',
  },

  // ============================================
  // SOURCE BLOCKS (merged from data-engineering & developer)
  // ============================================
  {
    id: 'stream_consume',
    type: 'stream_consume',
    label: 'Create Stream',
    description: 'Create & consume CDC stream on table/view',
    icon: GitBranch,
    category: 'source',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/20',
    borderColor: 'border-cyan-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Create a Snowflake Stream on a table or view to capture change data (CDC). The stream tracks INSERT, UPDATE, DELETE changes.',
  },

  // ============================================
  // TRANSFORM BLOCKS (code runner)
  // ============================================
  {
    id: 'sql_script',
    type: 'sql_script',
    label: 'SQL Script',
    description: 'Run custom SQL',
    icon: Code2,
    category: 'transform',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 4,
    tooltip: 'Execute custom SQL with inline editor and test button. Results are previewed (limited to 10 rows).',
  },
  {
    id: 'python_script',
    type: 'python_script',
    label: 'Python Script',
    description: 'Run Snowpark Python',
    icon: Hash,
    category: 'transform',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50 dark:bg-yellow-900/20',
    borderColor: 'border-yellow-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 4,
    tooltip: 'Execute Snowpark Python — call an existing stored procedure or write inline code. Supports testing with live output.',
  },
  {
    id: 'notebook_run',
    type: 'notebook_run',
    label: 'Run Notebook',
    description: 'Execute Snowflake notebook',
    icon: BookOpen,
    category: 'transform',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 1,
    tooltip: 'Execute a Snowflake Notebook and capture output',
  },

  // ============================================
  // DESTINATION BLOCKS (data engineering)
  // ============================================
  {
    id: 'dynamic_table',
    type: 'dynamic_table',
    label: 'Dynamic Table',
    description: 'Auto-refreshing materialized table',
    icon: RefreshCw,
    category: 'destination',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50 dark:bg-teal-900/20',
    borderColor: 'border-teal-400',
    hasInput: true,
    hasOutput: false,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Create a Snowflake Dynamic Table that auto-refreshes based on TARGET_LAG. Requires a warehouse and a SELECT query as the table definition.',
  },


  // ============================================
  // ADVANCED TRANSFORM BLOCKS — Window Functions
  // ============================================
  {
    id: 'window_rank',
    type: 'window_rank',
    label: 'Rank',
    description: 'RANK / DENSE_RANK / ROW_NUMBER',
    icon: Trophy,
    category: 'transform_advanced',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    borderColor: 'border-amber-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Add ranking columns with RANK(), DENSE_RANK(), or ROW_NUMBER() over partitions',
  },
  {
    id: 'window_lag_lead',
    type: 'window_lag_lead',
    label: 'Lag / Lead',
    description: 'Access previous/next rows',
    icon: ArrowLeftRight,
    category: 'transform_advanced',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Access previous (LAG) or next (LEAD) row values with configurable offset and default',
  },
  {
    id: 'window_aggregate',
    type: 'window_aggregate',
    label: 'Running Agg',
    description: 'Running SUM / AVG / COUNT',
    icon: TrendingUp,
    category: 'transform_advanced',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/20',
    borderColor: 'border-emerald-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Calculate running aggregates (SUM, AVG, COUNT, MIN, MAX) over a window frame',
  },
  {
    id: 'window_ntile',
    type: 'window_ntile',
    label: 'Percentile',
    description: 'NTILE buckets / percentiles',
    icon: Percent,
    category: 'transform_advanced',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Divide rows into N equal buckets using NTILE() for percentile analysis',
  },

  // ============================================
  // ADVANCED TRANSFORM BLOCKS — JSON / Semi-Structured
  // ============================================
  {
    id: 'json_flatten',
    type: 'json_flatten',
    label: 'Flatten JSON',
    description: 'Flatten nested JSON arrays/objects',
    icon: Braces,
    category: 'transform_advanced',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Flatten nested JSON arrays or objects using LATERAL FLATTEN with configurable path and mode',
  },
  {
    id: 'json_extract',
    type: 'json_extract',
    label: 'Extract JSON',
    description: 'Extract fields from JSON column',
    icon: Search,
    category: 'transform_advanced',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/20',
    borderColor: 'border-cyan-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Extract specific fields from a VARIANT/JSON column using dot-path notation (e.g., data:name::VARCHAR)',
  },
  {
    id: 'json_construct',
    type: 'json_construct',
    label: 'Build JSON',
    description: 'Build JSON object from columns',
    icon: Wrench,
    category: 'transform_advanced',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50 dark:bg-teal-900/20',
    borderColor: 'border-teal-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Construct a JSON object from selected columns using OBJECT_CONSTRUCT',
  },

  // ============================================
  // ADVANCED TRANSFORM BLOCKS — Pivot / Unpivot
  // ============================================
  {
    id: 'pivot',
    type: 'pivot',
    label: 'Pivot',
    description: 'Rows to columns',
    icon: RotateCcw,
    category: 'transform_advanced',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    borderColor: 'border-purple-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Pivot rows to columns — aggregate values for each distinct value in the pivot column',
  },
  {
    id: 'unpivot',
    type: 'unpivot',
    label: 'Unpivot',
    description: 'Columns to rows',
    icon: SplitSquareVertical,
    category: 'transform_advanced',
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
    borderColor: 'border-fuchsia-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Unpivot columns to rows — convert multiple columns into name-value pairs',
  },

  // ============================================
  // ADVANCED TRANSFORM BLOCKS — Date / Time
  // ============================================
  {
    id: 'date_transform',
    type: 'date_transform',
    label: 'Date Transform',
    description: 'DATEADD / DATEDIFF / TRUNC',
    icon: Calendar,
    category: 'transform_advanced',
    color: 'text-sky-600',
    bgColor: 'bg-sky-50 dark:bg-sky-900/20',
    borderColor: 'border-sky-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Date/time transformations: DATEADD, DATEDIFF, DATE_TRUNC, DATE_PART, LAST_DAY',
  },
  {
    id: 'time_slice',
    type: 'time_slice',
    label: 'Time Bucket',
    description: 'Group timestamps into buckets',
    icon: Timer,
    category: 'transform_advanced',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    borderColor: 'border-indigo-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Group timestamps into fixed-size buckets using TIME_SLICE (e.g., 5-minute, hourly, daily)',
  },

  // ============================================
  // ADVANCED TRANSFORM BLOCKS — Data Cleaning
  // ============================================
  {
    id: 'fill_nulls',
    type: 'fill_nulls',
    label: 'Fill Nulls',
    description: 'Replace NULL values',
    icon: Eraser,
    category: 'transform_advanced',
    color: 'text-rose-600',
    bgColor: 'bg-rose-50 dark:bg-rose-900/20',
    borderColor: 'border-rose-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Replace NULL values with a constant, forward-fill, backward-fill, mean, or median',
  },
  {
    id: 'case_when',
    type: 'case_when',
    label: 'Conditional',
    description: 'CASE WHEN logic builder',
    icon: GitCompare,
    category: 'transform_advanced',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    borderColor: 'border-green-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Build conditional logic visually: CASE WHEN condition1 THEN value1 WHEN condition2 THEN value2 ELSE default END',
  },
  {
    id: 'split_column',
    type: 'split_column',
    label: 'Split Column',
    description: 'Split text into multiple columns',
    icon: Columns,
    category: 'transform_advanced',
    color: 'text-lime-600',
    bgColor: 'bg-lime-50 dark:bg-lime-900/20',
    borderColor: 'border-lime-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Split a text column by delimiter into multiple output columns using SPLIT_PART',
  },
  {
    id: 'fuzzy_match',
    type: 'fuzzy_match',
    label: 'Fuzzy Match',
    description: 'EDIT_DISTANCE deduplication — find similar strings',
    icon: Search,
    category: 'transform_advanced',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 2,
    tooltip: 'Use EDITDISTANCE to find fuzzy matches between two columns for deduplication or record linking',
  },
  {
    id: 'json_path_extract',
    type: 'json_path_extract',
    label: 'JSON Path Extract',
    description: 'Extract nested JSON values with path expressions',
    icon: Braces,
    category: 'transform_advanced',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/20',
    borderColor: 'border-cyan-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Extract nested values from VARIANT/JSON columns using JSON_EXTRACT_PATH_TEXT',
  },
  {
    id: 'qualify_filter',
    type: 'qualify_filter',
    label: 'Qualify Filter',
    description: 'QUALIFY — filter rows after window functions',
    icon: Filter,
    category: 'transform_advanced',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    borderColor: 'border-amber-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Use QUALIFY clause to filter rows after window function evaluation — deduplicate with ROW_NUMBER',
  },
  {
    id: 'correlation',
    type: 'correlation',
    label: 'Correlation Matrix',
    description: 'CORR/COVAR — find correlated columns',
    icon: BarChart3,
    category: 'transform_advanced',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/20',
    borderColor: 'border-emerald-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Calculate Pearson correlation and covariance between two numeric columns using CORR/COVAR_SAMP',
  },
  {
    id: 'histogram',
    type: 'histogram',
    label: 'Distribution',
    description: 'HISTOGRAM — value distribution analysis',
    icon: BarChart,
    category: 'transform_advanced',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50 dark:bg-pink-900/20',
    borderColor: 'border-pink-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Analyze value distribution with WIDTH_BUCKET — create histogram buckets for numeric columns',
  },

  // ============================================
  // CLOUD / EXTERNAL SOURCE BLOCKS
  // ============================================
  {
    id: 's3_source',
    type: 's3_source',
    label: 'S3 Source',
    description: 'Read from AWS S3 via stage',
    icon: Cloud,
    category: 'source',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    borderColor: 'border-amber-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from AWS S3 via an external stage (CSV, JSON, Parquet)',
  },
  {
    id: 'azure_source',
    type: 'azure_source',
    label: 'Azure Source',
    description: 'Read from Azure Blob via stage',
    icon: Cloud,
    category: 'source',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from Azure Blob Storage via an external stage',
  },
  {
    id: 'gcs_source',
    type: 'gcs_source',
    label: 'GCS Source',
    description: 'Read from Google Cloud Storage',
    icon: Cloud,
    category: 'source',
    color: 'text-red-600',
    bgColor: 'bg-red-50 dark:bg-red-900/20',
    borderColor: 'border-red-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from Google Cloud Storage via an external stage',
  },
  {
    id: 'postgres_source',
    type: 'postgres_source',
    label: 'PostgreSQL',
    description: 'Read from PostgreSQL replication',
    icon: Database,
    category: 'source',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    borderColor: 'border-indigo-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a PostgreSQL table replicated via Snowflake native connector',
  },
  {
    id: 'mysql_source',
    type: 'mysql_source',
    label: 'MySQL',
    description: 'Read from MySQL replication',
    icon: Database,
    category: 'source',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a MySQL table replicated via Snowflake native connector',
  },
  {
    id: 'external_table_source',
    type: 'external_table_source',
    label: 'External Table',
    description: 'Read from external table',
    icon: ExternalLink,
    category: 'source',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/20',
    borderColor: 'border-emerald-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a Snowflake external table (backed by S3/Azure/GCS)',
  },
  {
    id: 'dynamic_table_source',
    type: 'dynamic_table_source',
    label: 'Dynamic Table',
    description: 'Read from dynamic table',
    icon: RefreshCw,
    category: 'source',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50 dark:bg-teal-900/20',
    borderColor: 'border-teal-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a Snowflake dynamic table (auto-refreshing materialized view)',
  },
  {
    id: 'shared_data_source',
    type: 'shared_data_source',
    label: 'Shared Data',
    description: 'Read from shared database',
    icon: Share2,
    category: 'source',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    borderColor: 'border-purple-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a Snowflake shared database (Data Sharing / Marketplace)',
  },

  // ============================================
  // CRM / ERP / SAAS SOURCE BLOCKS
  // ============================================
  {
    id: 'salesforce_source',
    type: 'salesforce_source',
    label: 'Salesforce',
    description: 'Read from Salesforce objects',
    icon: Cloud,
    category: 'source',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from Salesforce CRM objects (Accounts, Contacts, Opportunities, etc.)',
  },
  {
    id: 'sap_source',
    type: 'sap_source',
    label: 'SAP',
    description: 'Read from SAP tables',
    icon: Building2,
    category: 'source',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from SAP ERP tables via RFC/BAPI connector',
  },
  {
    id: 'oracle_source',
    type: 'oracle_source',
    label: 'Oracle DB',
    description: 'Read from Oracle Database',
    icon: Database,
    category: 'source',
    color: 'text-red-600',
    bgColor: 'bg-red-50 dark:bg-red-900/20',
    borderColor: 'border-red-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from an Oracle Database table',
  },
  {
    id: 'hubspot_source',
    type: 'hubspot_source',
    label: 'HubSpot',
    description: 'Read from HubSpot objects',
    icon: TrendingUp,
    category: 'source',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from HubSpot CRM objects (contacts, companies, deals, tickets)',
  },
  {
    id: 'servicenow_source',
    type: 'servicenow_source',
    label: 'ServiceNow',
    description: 'Read from ServiceNow tables',
    icon: Shield,
    category: 'source',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    borderColor: 'border-green-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from ServiceNow ITSM tables (incident, cmdb_ci, etc.)',
  },
  {
    id: 'api_source',
    type: 'api_source',
    label: 'REST API',
    description: 'Read from custom REST API',
    icon: Zap,
    category: 'source',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Read data from a custom REST API endpoint ingested via the Connect module',
  },
  {
    id: 'recursive_cte',
    type: 'recursive_cte',
    label: 'Recursive Hierarchy',
    description: 'Recursive CTE for org charts, BOM, tree structures',
    icon: GitBranch,
    category: 'source',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    borderColor: 'border-blue-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Build recursive CTE queries for hierarchical data — org charts, BOM, category trees',
  },

  // ============================================
  // PYTHON DATA ENGINEERING BLOCKS
  // ============================================
  {
    id: 'create_udf',
    type: 'create_udf',
    label: 'Create UDF',
    description: 'Create user-defined function',
    icon: Cog,
    category: 'python',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50 dark:bg-yellow-900/20',
    borderColor: 'border-yellow-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Create a Python/SQL/Java User-Defined Function (UDF) in Snowflake',
  },
  {
    id: 'create_procedure',
    type: 'create_procedure',
    label: 'Create Procedure',
    description: 'Create stored procedure',
    icon: Play,
    category: 'python',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    borderColor: 'border-green-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Create a Python stored procedure with Snowpark DataFrame API access',
  },
  {
    id: 'apply_udf',
    type: 'apply_udf',
    label: 'Apply UDF',
    description: 'Apply function to columns',
    icon: Zap,
    category: 'python',
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
    borderColor: 'border-fuchsia-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Apply a User-Defined Function to input columns inline in the pipeline',
  },

  // ============================================
  // ML TRAINING BLOCKS (Cortex AI)
  // ============================================
  {
    id: 'finetune_model',
    type: 'finetune',
    label: 'Fine-Tune LLM',
    description: 'Fine-tune a Cortex LLM with training data',
    icon: Brain,
    category: 'ml_training',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    borderColor: 'border-purple-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Fine-tune a Snowflake Cortex LLM (mistral, llama) with your training data table',
  },
  {
    id: 'train_classifier',
    type: 'classification_train',
    label: 'Train Classifier',
    description: 'Train supervised classification model',
    icon: Crosshair,
    category: 'ml_training',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    borderColor: 'border-indigo-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Train a SNOWFLAKE.ML.CLASSIFICATION model on labeled data for predictions',
  },
  {
    id: 'anomaly_detection',
    type: 'anomaly_detect',
    label: 'Anomaly Detection',
    description: 'Train anomaly detection on time-series',
    icon: Activity,
    category: 'ml_training',
    color: 'text-red-600',
    bgColor: 'bg-red-50 dark:bg-red-900/20',
    borderColor: 'border-red-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Train a SNOWFLAKE.ML.ANOMALY_DETECTION model on time-series data',
  },
  {
    id: 'forecast',
    type: 'forecast',
    label: 'Forecast',
    description: 'ML forecasting on numeric columns',
    icon: LineChart,
    category: 'ml_training',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50 dark:bg-teal-900/20',
    borderColor: 'border-teal-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Train a SNOWFLAKE.ML.FORECAST model for time-series predictions',
  },
  {
    id: 'document_ai',
    type: 'document_ai',
    label: 'Document AI',
    description: 'Extract structured data from documents',
    icon: FileSearch,
    category: 'ml_training',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    borderColor: 'border-orange-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Create a Document AI model to extract structured data from PDFs and images',
  },

  // AI SQL FUNCTIONS (Cortex SQL inline functions)
  {
    id: 'ai_classify',
    type: 'ai_classify',
    label: 'AI Classify',
    description: 'Classify text into categories using AI_CLASSIFY',
    icon: Tags,
    category: 'ai_functions',
    bgColor: 'bg-indigo-100 dark:bg-indigo-900/30',
    color: 'text-indigo-600 dark:text-indigo-400',
    borderColor: 'border-indigo-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Classify text columns into custom categories using Cortex AI_CLASSIFY SQL function',
  },
  {
    id: 'ai_sentiment',
    type: 'ai_sentiment',
    label: 'AI Sentiment',
    description: 'Analyze sentiment of text columns',
    icon: MessageSquare,
    category: 'ai_functions',
    bgColor: 'bg-pink-100 dark:bg-pink-900/30',
    color: 'text-pink-600 dark:text-pink-400',
    borderColor: 'border-pink-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Add sentiment score (-1 to 1) to text columns using AI_SENTIMENT',
  },
  {
    id: 'ai_translate',
    type: 'ai_translate',
    label: 'AI Translate',
    description: 'Translate text between languages',
    icon: Languages,
    category: 'ai_functions',
    bgColor: 'bg-cyan-100 dark:bg-cyan-900/30',
    color: 'text-cyan-600 dark:text-cyan-400',
    borderColor: 'border-cyan-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Translate text columns to another language using AI_TRANSLATE',
  },
  {
    id: 'ai_extract',
    type: 'ai_extract',
    label: 'AI Extract',
    description: 'Extract structured data from text',
    icon: FileSearch,
    category: 'ai_functions',
    bgColor: 'bg-emerald-100 dark:bg-emerald-900/30',
    color: 'text-emerald-600 dark:text-emerald-400',
    borderColor: 'border-emerald-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Extract structured fields from text using AI_EXTRACT',
  },
  {
    id: 'ai_complete',
    type: 'ai_complete',
    label: 'AI Complete',
    description: 'Generate text with LLM completion',
    icon: Sparkles,
    category: 'ai_functions',
    bgColor: 'bg-violet-100 dark:bg-violet-900/30',
    color: 'text-violet-600 dark:text-violet-400',
    borderColor: 'border-violet-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Generate text using AI_COMPLETE with a Cortex LLM model',
  },
  {
    id: 'ai_filter',
    type: 'ai_filter',
    label: 'AI Filter',
    description: 'AI_FILTER — natural language row filtering',
    icon: Sparkles,
    category: 'ai_functions',
    bgColor: 'bg-purple-100 dark:bg-purple-900/30',
    color: 'text-purple-600 dark:text-purple-400',
    borderColor: 'border-purple-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Filter rows using natural language conditions with Cortex AI_FILTER',
  },
  {
    id: 'ai_agg',
    type: 'ai_agg',
    label: 'AI Aggregate',
    description: 'AI_AGG — semantic group aggregation',
    icon: Sparkles,
    category: 'ai_functions',
    bgColor: 'bg-purple-100 dark:bg-purple-900/30',
    color: 'text-purple-600 dark:text-purple-400',
    borderColor: 'border-purple-400',
    hasInput: true,
    hasOutput: true,
    minInputs: 1,
    maxInputs: 1,
    tooltip: 'Aggregate text data semantically using Cortex AI_AGG — summarize grouped text with AI',
  },

  // ============================================
  // TEMPLATE BLOCKS — Prebuilt Common Patterns
  // ============================================
  {
    id: 'template_daily_refresh',
    type: 'template_daily_refresh',
    label: 'Daily Full Refresh',
    description: 'Source -> Filter -> Destination with daily CRON schedule',
    icon: Clock,
    category: 'templates',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Prebuilt pipeline: reads a source table, applies optional filters, and writes to a destination on a daily CRON schedule',
  },
  {
    id: 'template_incremental_merge',
    type: 'template_incremental_merge',
    label: 'Incremental Merge',
    description: 'Source -> Filter by watermark -> MERGE INTO target',
    icon: GitMerge,
    category: 'templates',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Prebuilt pipeline: reads new/changed rows using a watermark column, then MERGE INTO the target table with configurable merge keys',
  },
  {
    id: 'template_sentiment_pipeline',
    type: 'template_sentiment_pipeline',
    label: 'AI Sentiment Pipeline',
    description: 'Source -> AI Sentiment -> Destination with scores',
    icon: Sparkles,
    category: 'templates',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50 dark:bg-violet-900/20',
    borderColor: 'border-violet-400',
    hasInput: false,
    hasOutput: true,
    minInputs: 0,
    maxInputs: 0,
    tooltip: 'Prebuilt pipeline: reads a text column from source, runs AI_SENTIMENT to score each row, and writes results to a destination table',
  },
];

// Get blocks by category
export const getBlocksByCategory = (category: ETLCategory): ETLBlockDefinition[] => {
  return ETL_BLOCKS.filter((block) => block.category === category);
};

// Common blocks shown first in the palette for quick access
const COMMON_BLOCK_TYPES = ['source', 'filter', 'join', 'aggregate', 'select', 'formula', 'sort', 'destination'];
export const getCommonBlocks = (): ETLBlockDefinition[] => {
  return COMMON_BLOCK_TYPES.map((type) => ETL_BLOCKS.find((b) => b.type === type)).filter(Boolean) as ETLBlockDefinition[];
};

// Get block by type
export const getBlockByType = (type: string): ETLBlockDefinition | undefined => {
  return ETL_BLOCKS.find((block) => block.type === type);
};

// Category labels
export const CATEGORY_LABELS: Record<ETLCategory, string> = {
  source: 'Data Sources',
  transform: 'Basic Transforms',
  transform_advanced: 'Advanced Transforms',
  destination: 'Destinations',
  python: 'Python / UDF',
  ml_training: 'ML Training',
  ai_functions: 'AI Functions',
  templates: 'Templates',
};

// Category icons
export const CATEGORY_ICONS: Record<ETLCategory, LucideIcon> = {
  source: Database,
  transform: Calculator,
  transform_advanced: TrendingUp,
  destination: MapPin,
  python: Code2,
  ml_training: Brain,
  ai_functions: Sparkles,
  templates: Clock,
};

// ============================================
// LEGACY MAPPINGS (for backward compatibility)
// ============================================

// Map old node types to new types
export const LEGACY_TYPE_MAP: Record<string, string> = {
  src: 'source',
  join_tables: 'join',
  aggregate_kpi: 'aggregate',
  filter_rows: 'filter',
  drop_nulls: 'filter',
  drop_duplicates: 'distinct',
  deduplicate: 'distinct',
  normalize: 'formula',
  normalize_zscore: 'formula',
  normalize_minmax: 'formula',
  set_col_value: 'formula',
  rename_col: 'rename',
  export_excel: 'export_file',
  python_inline: 'python_script',
  copy_into: 'destination',
  merge: 'destination',
};

// Convert legacy node type to new type
export function convertLegacyType(legacyType: string): string {
  return LEGACY_TYPE_MAP[legacyType] || legacyType;
}
