import { chromium } from '@playwright/test';
const ABS='/Users/datalab360/Documents/data360_pro/datalab360Front';
const out = { non2xx:[], consoleErr:[], finalUrl:'', bodyLen:0, bodyHead:'' };
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: ABS+'/e2e/.auth/state.json' });
const pg = await ctx.newPage();
pg.on('console', m=>{ if(m.type()==='error') out.consoleErr.push(m.text().slice(0,160)); });
pg.on('response', r=>{ const s=r.status(); if(s>=400) out.non2xx.push(s+' '+r.request().method()+' '+r.url().replace('http://localhost:8000','').replace('http://localhost:3000','')); });
await pg.goto('http://localhost:3000/mapping', { waitUntil:'domcontentloaded', timeout:60000 });
await pg.waitForTimeout(9000);
out.finalUrl = pg.url();
const body = await pg.evaluate(()=>document.body.innerText);
out.bodyLen = body.length; out.bodyHead = body.slice(0,300);
await pg.screenshot({ path: ABS+'/docs/product-readiness-audit/screens/module-green/mapping.png', fullPage:true });
console.log(JSON.stringify(out,null,2));
await b.close();
