import { chromium } from '@playwright/test';
const ROOT='/Users/datalab360/Documents/data360_pro/datalab360Front';
const browser=await chromium.launch();
const ctx=await browser.newContext({storageState:ROOT+'/e2e/.auth/state.json'});
const page=await ctx.newPage();
const bad=[];
page.on('response',r=>{if(r.status()>=500)bad.push({s:r.status(),u:r.url()});});
await page.goto('http://localhost:3000/bi-dashboard/proj_f5ba1dffb392',{waitUntil:'networkidle',timeout:90000}).catch(e=>console.log('warn',String(e).slice(0,100)));
await page.waitForTimeout(8000);
await page.screenshot({path:ROOT+'/docs/product-readiness-audit/screens/module-green/bi-dashboard-proj.png',fullPage:true});
const t=await page.evaluate(()=>document.body.innerText);
console.log('>=500:',JSON.stringify(bad));
console.log('blank:',/Could not load|Failed to load|No widgets|No data|empty/i.test(t));
console.log('len',t.length);
console.log('nums:',JSON.stringify((t.match(/[\d,]+\.?\d+/g)||[]).filter(x=>x.replace(/\D/g,'').length>=4).slice(0,20)));
console.log('text:',t.slice(0,800).replace(/\n+/g,' | '));
await browser.close();
