import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:'e2e/.auth/state.json',viewport:{width:1600,height:1000}});
const p=await ctx.newPage();
const errs=[],bad=[];
p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,160));});
p.on('response',r=>{if(r.status()>=400)bad.push(r.status()+' '+r.url().replace(BASE,'').split('?')[0]);});
await p.goto(`${BASE}/administration?tab=apiHealth`,{waitUntil:'domcontentloaded',timeout:60000}).catch(e=>console.log('nav',e.message));
await p.waitForTimeout(8000);
const body=(await p.locator('body').innerText().catch(()=>'')).replace(/\s+/g,' ').trim();
console.log('BODY len',body.length,':',body.slice(0,260));
console.log('BAD responses:',bad.length); [...new Set(bad)].slice(0,12).forEach(x=>console.log('  ',x));
console.log('CONSOLE errors:',errs.length); [...new Set(errs)].slice(0,8).forEach(x=>console.log('  ',x));
await b.close();
