import { chromium } from '@playwright/test';
const BASE='http://localhost:3000', STATE='/Users/datalab360/Documents/data360_pro/datalab360Front/e2e/.auth/state-minted.json';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:STATE,viewport:{width:1700,height:1050}});
const p=await ctx.newPage();
const errs=[],net=[];
p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,140));});
p.on('response',r=>{if(r.status()>=400)net.push(r.status()+' '+r.url().replace(BASE,'').replace('/api-proxy','').split('?')[0]);});
await p.goto(`${BASE}/data-products`,{waitUntil:'domcontentloaded',timeout:120000}).catch(()=>{});
await p.waitForTimeout(20000);
const body=(await p.locator('body').innerText().catch(()=>'')).replace(/\s+/g,' ');
console.log('TRUST SCORE present:', body.includes('TRUST SCORE')||body.includes('Trust Score'));
console.log('has skeletons still:', body.includes('Loading')||/product/i.test(body));
const m=body.match(/TRUST SCORE\s*([0-9]+|—)/i); console.log('trust val:', m?m[1]:'(label not adjacent)');
console.log('4xx/5xx:', [...new Set(net)].slice(0,8).join(' | '));
console.log('console errors:'); [...new Set(errs)].slice(0,8).forEach(e=>console.log('  ',e));
await b.close();
