import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ storageState: 'e2e/.auth/state.json', viewport:{width:1600,height:1000} });
const page = await ctx.newPage();
const errs=[], cons=[], serverErr=[];
page.on('response', async (r)=>{ if(r.url().includes('data-quality')){ const s=r.status(); if(s>=500) serverErr.push({u:r.url().split('/api-proxy/').pop()||r.url(),s}); } });
page.on('console', m=>{ if(m.type()==='error') cons.push(m.text().slice(0,160)); });
page.on('pageerror', e=>errs.push(String(e).slice(0,160)));
await page.goto(`${BASE}/data-quality`, { waitUntil:'networkidle', timeout:60000 }).catch(e=>console.log('goto:',String(e).slice(0,100)));
await page.waitForTimeout(6000);
await page.screenshot({ path:'docs/product-readiness-audit/screens/module-green/data-quality.png', fullPage:true });
const bodyText = await page.evaluate(()=>document.body.innerText);
const hasErrPanel = /could not load|failed to load|something went wrong|no data available/i.test(bodyText);
// Pull a visible health score number if present
const scoreMatch = bodyText.match(/health\s*score[^0-9]{0,20}(\d+\.?\d*)/i) || bodyText.match(/(\d+\.?\d*)\s*%?\s*\n?\s*health/i);
console.log('--- DRIVE RESULT ---');
console.log('bodyTextLen', bodyText.length);
console.log('errorPanelPresent', hasErrPanel);
console.log('serverErrors', JSON.stringify(serverErr));
console.log('consoleErrors', cons.length, JSON.stringify(cons.slice(0,5)));
console.log('pageErrors', errs.length, JSON.stringify(errs.slice(0,5)));
console.log('healthScoreOnPage', scoreMatch?scoreMatch[1]:'(not found)');
console.log('bodySample', bodyText.slice(0,500).replace(/\n+/g,' | '));
await browser.close();
