import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:'e2e/.auth/state.json'});
const p=await ctx.newPage();
const e5=[], cerr=[], connectCalls=[];
p.on('response',x=>{const u=x.url(); if(x.status()>=500)e5.push(x.status()+' '+u.replace(/.*\/api-proxy/,'').slice(0,70)); if(u.includes('/connect/')||u.includes('/source-catalog')) connectCalls.push(x.status()+' '+u.replace(/.*(\/connect\/[^?]*|\/source-catalog)[^"]*/,'$1'));});
p.on('console',m=>{if(m.type()==='error')cerr.push(m.text().slice(0,100));});
await p.goto(`${BASE}/data-source-connection`,{waitUntil:'networkidle'}).catch(()=>{});
await p.waitForTimeout(6000);
const url=p.url().replace(BASE,'');
const body=await p.locator('body').innerText().catch(()=>'');
const hasErr=/could not load|failed to load|something went wrong/i.test(body);
const blank=body.trim().length<40;
const connectorWords=['Snowflake','Azure','AWS','PostgreSQL','MySQL','GCS','S3','Oracle'].filter(w=>body.includes(w));
await p.screenshot({path:'docs/product-readiness-audit/screens/module-green/data-source-connection.png',fullPage:true});
console.log('URL',url);
console.log('authed', !url.includes('/signin'));
console.log('blank',blank,'hasErrText',hasErr);
console.log('connectorWordsVisible',connectorWords.join(','));
console.log('bodyLen',body.length);
console.log('5xx',JSON.stringify(e5));
console.log('consoleErrs',JSON.stringify([...new Set(cerr)].slice(0,8)));
console.log('connectCalls',JSON.stringify([...new Set(connectCalls)]));
console.log('BODYSNIP', body.replace(/\s+/g,' ').slice(0,600));
await b.close();
