import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:'e2e/.auth/state.json'});
const p=await ctx.newPage();
const perr=[];
p.on('pageerror',e=>perr.push(e.message.slice(0,160)));
const resp=await p.goto(`${BASE}/data-source-connection`,{waitUntil:'load'}).catch(e=>({err:e.message}));
console.log('status',resp&&resp.status&&resp.status());
await p.waitForTimeout(8000);
console.log('finalURL',p.url());
const html=await p.content();
console.log('htmlLen',html.length);
console.log('hasNextRoot', html.includes('__next')||html.includes('__NEXT_DATA__'));
console.log('title',await p.title().catch(()=>''));
// look for any visible text via locator
const allText=await p.locator('div,span,h1,h2,p').allInnerTexts().catch(()=>[]);
console.log('visibleNodes',allText.filter(Boolean).length);
console.log('sample',JSON.stringify(allText.filter(Boolean).slice(0,20)));
console.log('pageerrors',JSON.stringify(perr.slice(0,5)));
console.log('HTMLSNIP',html.replace(/\s+/g,' ').slice(0,500));
await b.close();
