import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:'e2e/.auth/state.json'});
const p=await ctx.newPage();
const e5=[], connectCalls=[];
p.on('response',x=>{const u=x.url(); if(x.status()>=500)e5.push(x.status()+' '+u.slice(-70)); if(u.includes('/connect/')||u.includes('source-catalog')||u.includes('/databases')) connectCalls.push(x.status()+' '+(u.match(/(connect\/[^?]*|source-catalog|common\/databases)/)||[''])[0]);});
await p.goto(`${BASE}/data-source-connection`,{waitUntil:'domcontentloaded'}).catch(e=>console.log('gotoErr',e.message));
await p.waitForTimeout(12000);
const body=await p.evaluate(()=>document.body?document.body.innerText:'NOBODY').catch(e=>'EVALERR '+e.message);
const h1=await p.evaluate(()=>[...document.querySelectorAll('h1,h2,h3')].map(x=>x.innerText).slice(0,12)).catch(()=>[]);
const tabs=await p.locator('[role="tab"], button').allInnerTexts().catch(()=>[]);
await p.screenshot({path:'docs/product-readiness-audit/screens/module-green/data-source-connection.png',fullPage:true});
console.log('bodyLen',body.length);
console.log('headings',JSON.stringify(h1));
console.log('someButtons',JSON.stringify([...new Set(tabs)].filter(Boolean).slice(0,25)));
console.log('connectCalls',JSON.stringify([...new Set(connectCalls)]));
console.log('5xx',JSON.stringify(e5));
console.log('BODYSNIP', body.replace(/\s+/g,' ').slice(0,700));
await b.close();
