import { chromium } from '@playwright/test';
const BASE='http://localhost:3000', AUTH='e2e/.auth/state-minted.json';
const net=[];
const browser=await chromium.launch();
const ctx=await browser.newContext({storageState:AUTH, viewport:{width:1500,height:1000}});
const page=await ctx.newPage(); page.setDefaultTimeout(6000);
page.on('response',r=>{if(/dmf\/suggest/.test(r.url()))net.push(`${r.status()} ${r.request().method()} ${r.url().replace(BASE,'').split('?')[0]}`);});
await page.goto(`${BASE}/data-quality`,{waitUntil:'domcontentloaded'});
for(let i=0;i<35;i++){const h=await page.locator('h1').first().textContent().catch(()=>'')||'';if(/Data Quality/i.test(h))break;await page.waitForTimeout(1000);}
await page.waitForTimeout(2500);
await page.getByRole('button',{name:'DMF Results',exact:true}).first().click().catch(()=>{});
await page.waitForTimeout(1800);
await page.locator('table tbody tr').first().click().catch(e=>console.log('row',e.message.slice(0,30)));
await page.waitForTimeout(1200);
const sug=page.getByRole('button',{name:/Suggest/i}).first();
console.log('Suggest count:', await sug.count());
await sug.click().catch(e=>console.log('sug',e.message.slice(0,40)));
await page.waitForTimeout(3500);
const txt=await page.locator('.fixed, [role=dialog], aside, [role=alert]').filter({hasText:/suggest|fail|error|DMF/i}).allTextContents().catch(()=>[]);
console.log('RESULT:', JSON.stringify(txt.map(p=>p.replace(/\s+/g,' ').trim().slice(0,120)).slice(0,3)));
console.log('SUGGEST NET:', JSON.stringify(net));
await browser.close(); process.exit(0);
