import { chromium } from '@playwright/test';
const BASE='http://localhost:3000';
const b=await chromium.launch();
const ctx=await b.newContext({storageState:'e2e/.auth/state-minted.json',viewport:{width:1680,height:1000}});
const p=await ctx.newPage();
const net=[];
p.on('response',r=>{const s=r.status();if(s>=400)net.push(s+' '+r.request().method()+' '+r.url().replace(BASE,'').split('?')[0]);});
await p.goto(`${BASE}/explore-design`,{waitUntil:'domcontentloaded',timeout:60000}).catch(()=>{});
await p.waitForTimeout(6000);
await p.locator('button').filter({hasText:'SEED_EXP_RLS_MODEL'}).first().click().catch(()=>{});
await p.waitForTimeout(9000);
const dep=p.locator('button').filter({hasText:/^Deploy 11$|^Deploy$/}).first();
console.log('deploy found?',await dep.count(),'disabled?',await dep.isDisabled().catch(()=>'?'));
await dep.click().catch(e=>console.log('dep err',e.message));
await p.waitForTimeout(6000);
const bt=(await p.locator('body').innerText().catch(()=>'')).replace(/\s+/g,' ').trim();
console.log('DEPLOY VIEW [180:900]:',bt.slice(180,900));
const db=[...new Set((await p.locator('button:visible').allInnerTexts()).map(t=>t.replace(/\s+/g,' ').trim()).filter(x=>x&&x.length<48))];
console.log('DEPLOY buttons:',JSON.stringify(db.filter(x=>!/Overview|Connect|Workflow|Governance|BI Dash|Intelligence|Quality|Observ|Admin|HAHA|proj_|Account/.test(x))));
await p.screenshot({path:'docs/product-readiness-audit/screens/qa/ed-deploy-panel.png'});
console.log('4xx/5xx:',JSON.stringify([...new Set(net)]));
await b.close();
