import { chromium } from '@playwright/test';
const ROOT='/Users/datalab360/Documents/data360_pro/datalab360Front';
const OUT=process.env.CLAUDE_JOB_DIR + '/tmp';
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ storageState: ROOT+'/e2e/.auth/state.json', viewport:{width:1500,height:2200} });
const p = await ctx.newPage();
const timings={}; const t0=Date.now();
p.on('request', r => { const u=r.url(); if(/command-center|org-accounts/.test(u)){ timings[u]=timings[u]||{start:Date.now()-t0}; }});
p.on('response', r => { const u=r.url(); if(/command-center|org-accounts/.test(u)){ const e=timings[u]||(timings[u]={}); e.status=r.status(); e.done=Date.now()-t0; }});
await p.goto('http://localhost:3000/account-overview?tab=finops', { waitUntil:'domcontentloaded', timeout:45000 });
await p.waitForTimeout(30000);
const txt = await p.evaluate(()=>document.body.innerText);
const has=(s)=>txt.includes(s);
console.log('MARKERS', JSON.stringify({audit_detail:has('Audit détaillé'),warehouse:has('Coût par warehouse'),resume:has('résumé des drivers')}));
const slow=Object.entries(timings).map(([u,v])=>({ep:u.replace(/^.*api-proxy/,'').replace(/\?.*/,'').slice(0,40),st:v.status,ms:(v.done!=null?v.done-(v.start||0):'PENDING')})).sort((a,b)=>(b.ms===-0?0:0)|| (typeof b.ms==='number'?b.ms:99999)-(typeof a.ms==='number'?a.ms:99999));
console.log('CALLS', JSON.stringify(slow,null,0));
await p.screenshot({ path: OUT+'/finops2.png', fullPage:true });
console.log('SHOT', OUT+'/finops2.png');
await b.close();
