import { chromium } from '@playwright/test';
const root='/Users/datalab360/Documents/data360_pro/datalab360Front';
const out=[]; const errs=[]; const bad=[];
const b=await chromium.launch();
const ctx=await b.newContext({storageState:root+'/e2e/.auth/state.json'});
const p=await ctx.newPage();
p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,160));});
p.on('response',r=>{if(r.status()>=500)bad.push(r.status()+' '+r.url());});
await p.goto('http://localhost:3000/workflow',{waitUntil:'networkidle',timeout:60000}).catch(e=>out.push('goto-err '+e.message));
await p.waitForTimeout(6000);
await p.screenshot({path:root+'/docs/product-readiness-audit/screens/module-green/workflow.png',fullPage:false});
const body=await p.evaluate(()=>document.body.innerText);
const empties=['Could not load','Failed to load','No data','Something went wrong','Error loading','blank'].filter(s=>body.includes(s));
out.push('TITLE: '+(await p.title()));
out.push('bodyLen: '+body.length);
out.push('emptyMarkers: '+JSON.stringify(empties));
out.push('5xx: '+JSON.stringify(bad.slice(0,10)));
out.push('consoleErrs: '+JSON.stringify(errs.slice(0,8)));
out.push('bodySample: '+body.replace(/\s+/g,' ').slice(0,700));
console.log(out.join('\n'));
await b.close();
