#!/usr/bin/env bash
# Scan & audit files unnecessary for PRODUCTION. Reports by default; deletes with --apply.
# Run from a repo root:  ../deploy/scripts/audit-unused.sh [--apply] [--docs]
#   (no flag) = dry-run report only          --apply = actually delete
#   --docs    = also flag *.md / docs/ (kept by default; docs aren't "unnecessary" per se)
#
# Safe by design: only removes build artifacts, caches, backups, logs, and clearly-throwaway
# AI/test scaffolding. It does NOT guess at "unused source" — for that use knip / ts-prune /
# vulture (see deploy/README.md), which produce a reviewed list, never an auto-delete.
set -uo pipefail
APPLY=0; DOCS=0
for a in "$@"; do [ "$a" = "--apply" ] && APPLY=1; [ "$a" = "--docs" ] && DOCS=1; done

# artifact/cache/backup patterns — always safe to drop (regenerated by build)
PATTERNS=(
  "-name __pycache__ -type d" "-name '*.pyc'" "-name '*.pyo'" "-name '.pytest_cache' -type d"
  "-name '.mypy_cache' -type d" "-name '.ruff_cache' -type d" "-name '.next' -type d"
  "-name '.turbo' -type d" "-name 'dist' -type d" "-name 'coverage' -type d" "-name '.nyc_output' -type d"
  "-name '*.log'" "-name '*.bak'" "-name '*.bak-*'" "-name '*.orig'" "-name '*.tmp'"
  "-name '.DS_Store'" "-name 'Thumbs.db'" "-name '*.swp'" "-name 'npm-debug.log*'"
)
# throwaway AI/test scaffolding (verification probes, mockups) — review before --apply
THROWAWAY=(
  "-path '*/e2e/_*.mjs'" "-path '*/e2e/_*.js'" "-name '*.mock.*'"
  "-name '*_probe.*'" "-name '*-verify*.mjs'" "-name '*.forensic.*'"
)
DOCPATTERNS=( "-name '*.md' -not -name 'README.md'" "-path '*/docs/*'" "-path '*/mockups/*'" )

total=0; bytes=0
scan(){
  local label="$1"; shift; local -n arr=$1
  echo; echo "── $label ──"
  for pat in "${arr[@]}"; do
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      local sz; sz=$(du -sk "$f" 2>/dev/null | cut -f1); bytes=$((bytes+${sz:-0})); total=$((total+1))
      printf '  %-8s %s\n' "${sz:-0}KB" "$f"
      [ $APPLY -eq 1 ] && rm -rf "$f"
    done < <(eval "find . -not -path './.git/*' -not -path './node_modules/*' $pat 2>/dev/null")
  done
}
echo "Audit @ $(pwd)  —  mode: $([ $APPLY -eq 1 ] && echo APPLY-DELETE || echo dry-run)"
scan "Build artifacts / caches / backups (safe)" PATTERNS
scan "Throwaway AI/test scaffolding (review)" THROWAWAY
[ $DOCS -eq 1 ] && scan "Docs / markdown / mockups (--docs)" DOCPATTERNS

echo; echo "── Secret / weight red-flags (report only) ──"
git ls-files 2>/dev/null | grep -E '(^|/)\.env$' | sed 's/^/  TRACKED SECRET: /' || true
find . -not -path './.git/*' -name 'node_modules' -type d 2>/dev/null | sed 's/^/  vendored (rebuild in image, dockerignore): /'
find . -not -path './.git/*' -name '.venv' -type d 2>/dev/null | sed 's/^/  vendored venv (dockerignore): /'

echo; printf 'Total: %d items, ~%d MB.  ' "$total" "$((bytes/1024))"
[ $APPLY -eq 1 ] && echo "DELETED." || echo "Re-run with --apply to delete (and --docs to include markdown)."
